inherit_from:
  - .rubocop_airbnb.yml
  
  # Rails用に最適化
Rails:
  Enabled: true

# 文字数の上限を８０文字から変更
LineLength:
  Max: 150

#以下にはrubocopで検証したくないフォルダを指定する
AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    
Airbnb/DefaultScope:
  Enabled: false
  
Airbnb/OptArgParameters:
  Enabled: false
  
Naming/AsciiIdentifiers:
  Enabled: false
